apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulp-cli-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulp-cli-test
  template:
    metadata:
      labels:
        app: pulp-cli-test
    spec:
      containers:
      - name: ubi9-test
        image: registry.access.redhat.com/ubi9/ubi:latest
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 30; done"]
        volumeMounts:
        - name: pulp-access
          mountPath: /etc/pulp-cli
          readOnly: true
        env:
        - name: PULP_CLI_CONFIG
          value: "/etc/pulp-cli/cli.toml"
      volumes:
      - name: pulp-access
        secret:
          secretName: pulp-access
      restartPolicy: Always
