apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pulp-access-operator
  namespace: operators
subjects:
  - kind: ServiceAccount
    name: pulp-access-operator
roleRef:
  kind: Role
  name: pulp-access-operator
  apiGroup: rbac.authorization.k8s.io

