apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulpaccess-operator-role
rules:
  - apiGroups: ["konflux.io"]
    resources: ["pulpaccessrequests"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "events", "pods"]
    verbs: ["create", "update", "patch"]
  - apiGroups: ["appstudio.redhat.com"]
    resources: ["imagerepositories"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

