apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulp-access-operator
  namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulpaccess-operator-binding
subjects:
  - kind: ServiceAccount
    name: pulp-access-operator
    namespace: operators
roleRef:
  kind: ClusterRole
  name: pulpaccess-operator-role
  apiGroup: rbac.authorization.k8s.io

