---
apiVersion: v1
kind: Namespace
metadata:
  name: pulp-access-controller
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pulpaccessrequests.pulp.konflux-ci.dev
spec:
  group: pulp.konflux-ci.dev
  scope: Namespaced
  names:
    plural: pulpaccessrequests
    singular: pulpaccessrequest
    kind: PulpAccessRequest
    shortNames:
      - par
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulp-access-operator
  namespace: pulp-access-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulpaccess-operator-role
rules:
  - apiGroups: ["pulp.konflux-ci.dev"]
    resources: ["pulpaccessrequests"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "events"]
    verbs: ["create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulpaccess-user-role
rules:
  - apiGroups: ["pulp.konflux-ci.dev"]
    resources: ["pulpaccessrequests"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulpaccess-operator-binding
subjects:
  - kind: ServiceAccount
    name: pulp-access-operator
    namespace: pulp-access-controller
roleRef:
  kind: ClusterRole
  name: pulpaccess-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pulp-secrets
  namespace: pulp-access-controller
  annotations:
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: stonesoup/staging/pulp/pulp-access-controller
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: pulp-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulp-access-operator
  namespace: pulp-access-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulp-access-operator
  template:
    metadata:
      labels:
        app: pulp-access-operator
    spec:
      serviceAccountName: pulp-access-operator
      securityContext:
         runAsNonRoot: true
      containers:
        - name: operator
          image: quay.io/ytrahnov/test-controller:v1.0.1
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env: []
          envFrom:
            - secretRef:
                name: pulp-secrets
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}